on:
  pull_request:
    types: [opened, synchronize]

jobs:
  java-spring-petclinic:
    runs-on: ubuntu-latest
    name: ChatGPT explain code
    steps:
      - name: ChatGTP explain code
        uses: interactivedevops/codereview@develop
        with:
          SONARQUBE_PROJECT_KEY: ${{ secrets.SONARQUBE_PROJECT_KEY }}
          GITHUB_PR_ID: ${{ github.event.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
